# Generated by Django 5.2.17 on 2026-09-29 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parca_markalari/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Parça Markası',
                'verbose_name_plural': 'Parça Markaları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='arac_markalari/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Araç Markası',
                'verbose_name_plural': 'Araç Markaları',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='slug')),
                ('aciklama', models.TextField(blank=True, verbose_name='açıklama')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='kategoriler/', verbose_name='görsel')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('ust_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategoriler', to='catalog.category', verbose_name='üst kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('parca_numarasi', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='parça numarası')),
                ('aciklama', models.TextField(blank=True, verbose_name='açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='fiyat')),
                ('stok_adedi', models.PositiveIntegerField(default=0, verbose_name='stok adedi')),
                ('ana_gorsel', models.ImageField(blank=True, null=True, upload_to='urunler/', verbose_name='ana görsel')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='aktif mi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urunler', to='catalog.category', verbose_name='kategori')),
                ('parca_markasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urunler', to='catalog.partbrand', verbose_name='parça markası')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil_baslangic', models.PositiveIntegerField(blank=True, null=True, verbose_name='yıl başlangıç')),
                ('yil_bitis', models.PositiveIntegerField(blank=True, null=True, verbose_name='yıl bitiş')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyumluluklar', to='catalog.product', verbose_name='ürün')),
            ],
            options={
                'verbose_name': 'Uyumluluk',
                'verbose_name_plural': 'Uyumluluklar',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(upload_to='urun_gorselleri/', verbose_name='görsel')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorseller', to='catalog.product', verbose_name='ürün')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='ad')),
                ('slug', models.SlugField(blank=True, max_length=120, verbose_name='slug')),
                ('uretim_baslangic_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='üretim başlangıç yılı')),
                ('uretim_bitis_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='üretim bitiş yılı')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeller', to='catalog.vehiclebrand', verbose_name='marka')),
            ],
            options={
                'verbose_name': 'Araç Modeli',
                'verbose_name_plural': 'Araç Modelleri',
                'ordering': ['marka__ad', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='uyumlu_modeller',
            field=models.ManyToManyField(blank=True, related_name='uyumlu_urunler', through='catalog.Fitment', to='catalog.vehiclemodel', verbose_name='uyumlu modeller'),
        ),
        migrations.AddField(
            model_name='fitment',
            name='arac_modeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyumluluklar', to='catalog.vehiclemodel', verbose_name='araç modeli'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('marka', 'slug'), name='benzersiz_marka_slug'),
        ),
        migrations.AddConstraint(
            model_name='fitment',
            constraint=models.UniqueConstraint(fields=('urun', 'arac_modeli', 'yil_baslangic', 'yil_bitis'), name='benzersiz_uyumluluk'),
        ),
    ]
