# Generated by Django 5.2.17 on 2026-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='aciklama_es',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='aciklama_fr',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_en',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_es',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_ar',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_en',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_es',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_fr',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_tr',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_es',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
    ]
