# Generated by Django 5.2.17 on 2026-10-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_gorsel_zorunlu'),
    ]

    operations = [
        # Fiyat bilgisi siteden tamamen kaldırıldı. Silmeden önce varsayılan
        # veriliyor ki migration geri alınabilsin (kolon 0 ile geri gelir;
        # silinen fiyatlar geri gelmez).
        migrations.AlterField(
            model_name='product',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='fiyat'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='fiyat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uyumlu_modeller',
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='özellik')),
                ('ad_tr', models.CharField(max_length=100, null=True, verbose_name='özellik')),
                ('ad_en', models.CharField(max_length=100, null=True, verbose_name='özellik')),
                ('ad_fr', models.CharField(max_length=100, null=True, verbose_name='özellik')),
                ('ad_es', models.CharField(max_length=100, null=True, verbose_name='özellik')),
                ('ad_ar', models.CharField(max_length=100, null=True, verbose_name='özellik')),
                ('deger', models.CharField(max_length=200, verbose_name='değer')),
                ('deger_tr', models.CharField(max_length=200, null=True, verbose_name='değer')),
                ('deger_en', models.CharField(max_length=200, null=True, verbose_name='değer')),
                ('deger_fr', models.CharField(max_length=200, null=True, verbose_name='değer')),
                ('deger_es', models.CharField(max_length=200, null=True, verbose_name='değer')),
                ('deger_ar', models.CharField(max_length=200, null=True, verbose_name='değer')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozellikler', to='catalog.product', verbose_name='ürün')),
            ],
            options={
                'verbose_name': 'Ürün Özelliği',
                'verbose_name_plural': 'Ürün Özellikleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='ör. 2.0 TDCi, 1.6 i-VTEC', max_length=100, verbose_name='ad')),
                ('motor_hacmi', models.DecimalField(blank=True, decimal_places=1, help_text='Litre cinsinden, ör. 2.0', max_digits=3, null=True, verbose_name='motor hacmi (L)')),
                ('kasa_tipi', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('station_wagon', 'Station Wagon'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('cabrio', 'Cabrio'), ('pickup', 'Pickup'), ('panelvan', 'Panelvan'), ('minibus', 'Minibüs'), ('kamyonet', 'Kamyonet')], max_length=20, verbose_name='kasa tipi')),
                ('uretim_baslangic_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='üretim başlangıç yılı')),
                ('uretim_bitis_yili', models.PositiveIntegerField(blank=True, null=True, verbose_name='üretim bitiş yılı')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiyonlar', to='catalog.vehiclemodel', verbose_name='model')),
            ],
            options={
                'verbose_name': 'Araç Versiyonu',
                'verbose_name_plural': 'Araç Versiyonları',
                'ordering': ['model__marka__ad', 'model__ad', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='fitment',
            name='arac_versiyonu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uyumluluklar', to='catalog.vehicleversion', verbose_name='araç versiyonu'),
        ),
        # 0007'de kaldırılacak. Burada (veri migration'ı 0006'dan ÖNCE)
        # nullable yapılıyor ki geri alırken sıra doğru olsun: 0007'nin tersi
        # alanı boş olarak geri ekler, 0006'nın tersi doldurur, ancak en son
        # bu adımın tersi onu tekrar zorunlu yapar.
        migrations.AlterField(
            model_name='fitment',
            name='arac_modeli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uyumluluklar', to='catalog.vehiclemodel', verbose_name='araç modeli'),
        ),
    ]
