# Generated by Django 5.2.17 on 2026-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_kategori_cevirileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='category',
            name='ad_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='product',
            name='aciklama_ru',
            field=models.TextField(blank=True, null=True, verbose_name='açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='ad_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='ad_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='özellik'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='deger_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='değer'),
        ),
    ]
