# Generated by Django 5.2.17 on 2026-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0002_baslangic_icerigi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sayfabasligi',
            options={'ordering': ['id'], 'verbose_name': 'Sayfa Başlığı ve Fotoğrafı', 'verbose_name_plural': 'Sayfa Başlıkları ve Fotoğrafları'},
        ),
        migrations.AlterField(
            model_name='sayfabasligi',
            name='gorsel',
            field=models.ImageField(blank=True, help_text="Sayfanın en üstünde olduğu gibi (efektsiz) gösterilir. Yatay, en az 1600 piksel genişliğinde bir fotoğraf önerilir. Boşsa Site Ayarları'ndaki varsayılan üst fotoğraf kullanılır.", upload_to='sayfa_basliklari/', verbose_name='üst fotoğraf'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='varsayilan_sayfa_gorseli',
            field=models.ImageField(blank=True, help_text="Sayfa Başlıkları'nda kendi fotoğrafı yüklenmemiş tüm sayfaların (ana sayfa dahil) üstünde gösterilir. Bir sayfaya özel fotoğraf için: Site İçeriği → Sayfa Başlıkları.", upload_to='site/', verbose_name='varsayılan üst fotoğraf'),
        ),
    ]
