# Generated by Django 5.2.17 on 2026-10-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0003_admin_etiketleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayfabasligi',
            name='slayt_suresi',
            field=models.PositiveSmallIntegerField(default=6, help_text='Sadece ana sayfa: her fotoğrafın ekranda kalma süresi.', verbose_name='slayt süresi (saniye)'),
        ),
        migrations.AlterField(
            model_name='sayfabasligi',
            name='gorsel',
            field=models.ImageField(blank=True, help_text="Sayfanın en üstünde, başlığın arkasında gösterilir. Yatay, en az 1600 piksel genişliğinde bir fotoğraf önerilir. Boşsa Site Ayarları'ndaki varsayılan üst fotoğraf kullanılır.", upload_to='sayfa_basliklari/', verbose_name='üst fotoğraf'),
        ),
        migrations.AlterField(
            model_name='siteayarlari',
            name='varsayilan_sayfa_gorseli',
            field=models.ImageField(blank=True, help_text='Kendi fotoğrafı yüklenmemiş sayfaların (ana sayfa hariç) üstünde gösterilir. Ana sayfanın fotoğrafları: Site İçeriği → Sayfa Başlıkları ve Fotoğrafları → Ana Sayfa → Slaytlar.', upload_to='site/', verbose_name='varsayılan üst fotoğraf'),
        ),
        migrations.CreateModel(
            name='HeroSlayt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorsel', models.ImageField(help_text='Yatay, en az 1600 piksel genişliğinde bir fotoğraf önerilir.', upload_to='hero/', verbose_name='fotoğraf')),
                ('ust_baslik', models.CharField(blank=True, max_length=80, verbose_name='üst başlık')),
                ('ust_baslik_tr', models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık')),
                ('ust_baslik_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık')),
                ('ust_baslik_fr', models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık')),
                ('ust_baslik_es', models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık')),
                ('ust_baslik_ar', models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık')),
                ('baslik', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, verbose_name='başlık')),
                ('baslik_tr', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık')),
                ('baslik_en', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık')),
                ('baslik_fr', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık')),
                ('baslik_es', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık')),
                ('baslik_ar', models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık')),
                ('baslik_vurgu', models.CharField(blank=True, max_length=100, verbose_name='başlığın renkli kısmı')),
                ('baslik_vurgu_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı')),
                ('baslik_vurgu_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı')),
                ('baslik_vurgu_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı')),
                ('baslik_vurgu_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı')),
                ('baslik_vurgu_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı')),
                ('alt_baslik', models.TextField(blank=True, verbose_name='alt başlık')),
                ('alt_baslik_tr', models.TextField(blank=True, null=True, verbose_name='alt başlık')),
                ('alt_baslik_en', models.TextField(blank=True, null=True, verbose_name='alt başlık')),
                ('alt_baslik_fr', models.TextField(blank=True, null=True, verbose_name='alt başlık')),
                ('alt_baslik_es', models.TextField(blank=True, null=True, verbose_name='alt başlık')),
                ('alt_baslik_ar', models.TextField(blank=True, null=True, verbose_name='alt başlık')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='yayında')),
                ('sayfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaytlar', to='icerik.sayfabasligi', verbose_name='sayfa')),
            ],
            options={
                'verbose_name': 'Slayt',
                'verbose_name_plural': 'Slaytlar (birden fazla eklenirse sırayla değişir)',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
