# Generated by Django 5.2.17 on 2026-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerik', '0004_hero_slaytlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslayt',
            name='alt_baslik_ru',
            field=models.TextField(blank=True, null=True, verbose_name='alt başlık'),
        ),
        migrations.AddField(
            model_name='heroslayt',
            name='baslik_ru',
            field=models.CharField(blank=True, help_text='Boşsa ana sayfa başlığı kullanılır.', max_length=150, null=True, verbose_name='başlık'),
        ),
        migrations.AddField(
            model_name='heroslayt',
            name='baslik_vurgu_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='başlığın renkli kısmı'),
        ),
        migrations.AddField(
            model_name='heroslayt',
            name='ust_baslik_ru',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='üst başlık'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='hakkimizda_baslik_ru',
            field=models.CharField(default='Hakkımızda', max_length=150, null=True, verbose_name='Hakkımızda başlığı'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='hakkimizda_metin_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımızda metni'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='misyon_baslik_ru',
            field=models.CharField(default='Misyonumuz', max_length=150, null=True, verbose_name='Misyon başlığı'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='misyon_metin_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Misyon metni'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='neden_biz_baslik_ru',
            field=models.CharField(default='Neden Biz?', max_length=150, null=True, verbose_name='Neden Biz başlığı'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='neden_biz_maddeleri_ru',
            field=models.TextField(blank=True, help_text="Her satıra bir madde yazın. İsterseniz 'Başlık: açıklama' şeklinde yazabilirsiniz.", null=True, verbose_name='Neden Biz maddeleri'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='vizyon_baslik_ru',
            field=models.CharField(default='Vizyonumuz', max_length=150, null=True, verbose_name='Vizyon başlığı'),
        ),
        migrations.AddField(
            model_name='kurumsalsayfa',
            name='vizyon_metin_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Vizyon metni'),
        ),
        migrations.AddField(
            model_name='sayfabasligi',
            name='alt_baslik_ru',
            field=models.TextField(blank=True, null=True, verbose_name='alt başlık'),
        ),
        migrations.AddField(
            model_name='sayfabasligi',
            name='baslik_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='başlık'),
        ),
        migrations.AddField(
            model_name='sayfabasligi',
            name='baslik_vurgu_ru',
            field=models.CharField(blank=True, help_text="Başlığın devamı olarak marka renginde gösterilir (ör. 'Tek Adreste').", max_length=100, null=True, verbose_name='başlığın renkli kısmı'),
        ),
        migrations.AddField(
            model_name='sayfabasligi',
            name='ust_baslik_ru',
            field=models.CharField(blank=True, help_text='Başlığın üstündeki küçük renkli yazı (ör. KALİTE VE GÜVEN).', max_length=80, null=True, verbose_name='üst başlık'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='adres_ru',
            field=models.TextField(blank=True, default='Örnek Mahallesi, Sanayi Caddesi No: 1\nİstanbul, Türkiye', null=True, verbose_name='adres'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='calisma_saatleri_ru',
            field=models.CharField(blank=True, default='Pazartesi – Cumartesi, 09:00 – 18:00', max_length=120, null=True, verbose_name='çalışma saatleri'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='footer_aciklama_ru',
            field=models.TextField(blank=True, default='Kaliteli ürünler ve güvenilir hizmet için doğru adres.', null=True, verbose_name='footer açıklaması'),
        ),
        migrations.AddField(
            model_name='siteayarlari',
            name='meta_aciklama_ru',
            field=models.CharField(blank=True, default='MARKA — kaliteli ürünler ve güvenilir hizmet.', max_length=200, null=True, verbose_name='site açıklaması (arama motorları)'),
        ),
    ]
